apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: smtp-sink
  namespace: default  
  labels:
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/part-of: spring-smtp-gateway
spec:
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-1
  source:
    git:
      ref:
        branch: main
      url: https://github.com/smachida/spring-smtp-gateway.git
    subPath: spring-smtp-gateway/smtp-sink
